version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      ["--log-output=TABLE", "--long_query_time=1", "--slow_query_log=ON"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 1e9b6ef3ac9ecb8a1e2b6f31b431ff534bc6357e0cd0348031f1e0be9ab644af
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_MONGODB_URI: mongodb://mongo:27017/graylog
    depends_on:
      - elasticsearch
      - mongo
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    volumes:
      - graylog_data:/etc/graylog/server

  mongo:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mysql-data:
  es-data:
  graylog_data:
  mongo_data:
